In [1]:
# Numpy Practice Questions
# 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
import numpy as np

A = np.array([1,2,3,4])
B = np.array([3,4,5,6])

np.vstack([A,B])

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [2]:
np.hstack([A,B])

array([1, 2, 3, 4, 3, 4, 5, 6])

In [3]:
# 2. Find common elements between A and B. [Hint : Intersection of two sets]
common = np.intersect1d(A, B)
print("Common elements between A and B:", common)

Common elements between A and B: [3 4]


In [4]:
# 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
mask = (A >= 2) & (A <= 4)
result = A[mask]
print(result)

[2 3 4]


In [5]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [6]:
# Practice Questions for Pandas
# 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [7]:
# 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
min_mean = df['Min.Price'].mean()
max_mean = df['Max.Price'].mean()

df['Min.Price'].fillna(min_mean, inplace=True)
df['Max.Price'].fillna(max_mean, inplace=True)

print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


In [8]:
# 3. How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
filtered_rows = df[df.sum(axis=1) > 100]
print(filtered_rows)

     0   1   2   3
0   20  31  21  39
2   26  38  36  33
4   34  28  33  13
5   29  39  29  16
6   35  26  36  11
7   15  33  34  31
9   22  37  25  25
12  28  39  21  39
13  35  14  37  38
14  30  37  22  19
